import { Request, Response } from "express";
import { groceryItemSchema } from "../utils/joi-edit-user-schema";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export async function getAllGroceryItem(req: Request, res: Response) {
  const GroceryItem = prisma.groceryItem;
  try {
    const groceryItems = await prisma.groceryItem.findMany({
      take: 10, // Limit to 10 items
      orderBy: {
        createdAt: 'desc', // Sort by createdAt in descending order
      },
      // If you want to select specific fields, you can use the 'select' option:
      // select: {
      //   id: true,
      //   name: true,
      //   category: true,
      //   price: true,
      //   quantityInStock: true,
      //   createdAt: true,
      //   updatedAt: true,
      // },
    });

    return res.status(200).json(groceryItems); // Use .json() for sending JSON response

  } catch (err) {
    console.error("Error fetching grocery items:", err);
    return res.status(500).json({ error: "Failed to fetch grocery items" }); // Send error as JSON
  } finally {
    await prisma.$disconnect(); // Disconnect Prisma client after use
  }
}

export async function createGroceryItem(req: Request, res: Response) {
  const item = req.body;
  const userId = req.body.decodedToken?.userId;

  if (!item) {
    return res.status(400).json({ error: "Item data is required" });
  }

  if (!userId) {
    return res.status(401).json({ error: "User authentication required" });
  }

  try {
    const price = parseFloat(item.price);
    const quantityInStock = parseInt(item.quantityInStock);
    const id = parseInt(userId);


    // Basic check to ensure conversion was successful
    if (isNaN(price)) {
      return res.status(400).json({ error: "Price must be a valid number" });
    }
    if (isNaN(quantityInStock)) {
      return res.status(400).json({ error: "Quantity in stock must be a valid integer" });
    }
    if (isNaN(id)) {
      return res.status(400).json({ error: "User ID must be a valid integer" });
    }

    const data = await prisma.groceryItem.create({
      data: {
        name: item.name,
        category: item.category,
        price: price, // Use the converted float value
        quantityInStock: quantityInStock, // Use the converted integer value
        id: id,
        // You should likely remove the 'id' from the create data,
        // as it's usually auto-generated by the database
        // id: parseInt(item.id), // Remove this unless you have a specific reason
      },
    });
    return res
      .status(201)
      .json({ data: data, message: "Item created successfully" });
  } catch (error: any) {
    console.error("Error creating grocery item:", error);
    res.status(500).json({ error: error.message || "Failed to create grocery item" });
  } finally {
    await prisma.$disconnect();
  }
}

export async function updateGroceryItem(req: Request, res: Response) {
  const validData = groceryItemSchema.validate(req.body);
  if (validData.error) {
    return res.status(400).json({ error: validData.error.details[0].message });
  }

  const item = req.body;
  const userId = req.body.decodedToken?.userId;
  delete item.decodedToken;


  if (!item || !item.id) {
    return res.status(400).json({ error: "Item data with ID is required" });
  }

  try {

    const price = item.price !== undefined ? parseFloat(item.price) : undefined;
    const quantityInStock = item.quantityInStock !== undefined ? parseInt(item.quantityInStock) : undefined;
    // Basic checks to ensure conversion was successful if the fields are provided
    if (item.price !== undefined && isNaN(price!)) {
      return res.status(400).json({ error: "Price must be a valid number" });
    }
    if (item.quantityInStock !== undefined && isNaN(quantityInStock!)) {
      return res.status(400).json({ error: "Quantity in stock must be a valid integer" });
    }


    const updateData: any = {
      name: item.name,
      category: item.category,
      // Only include price and quantityInStock if they are provided in the request
      ...(price !== undefined && { price: price }),
      ...(quantityInStock !== undefined && { quantityInStock: quantityInStock }),
      // Add other fields you want to update here
    };

    const data = await prisma.groceryItem.update({
      where: {
        id: parseInt(item.id), // Assuming your Prisma model uses an Int for the id field
        // You might want to add a condition to ensure the user owns the item
        // userId: userId,
      },
      data: updateData,
    });
    console.log("data ==== ", data);
    return res
      .status(200)
      .json({ data: data, message: "Item updated successfully" });
  } catch (error: any) {
    console.error("Error updating grocery item:", error);
    return res.status(500).json({ error: error.message || "Failed to update grocery item" });
  } finally {
    await prisma.$disconnect();
  }
}


export async function deleteGroceryItem(req: Request, res: Response) {
  const { id } = req.params;

  if (!id) {
    return res.status(400).json({ error: "Item ID is required" });
  }

  try {
    const data = await prisma.groceryItem.delete({
      where: {
        id: parseInt(id), // Assuming your Prisma model uses an Int for the id field
        // You might want to add a condition to ensure the user owns the item before deleting
        // userId: req.body.decodedToken.userId,
      },
    });

    if (data) {
      return res.status(200).json({ message: "Item deleted successfully" });
    } else {
      return res.status(404).json({ error: "Item not found" }); // Or handle as appropriate
    }
  } catch (error: any) {
    console.error("Error deleting grocery item:", error);
    return res.status(500).json({ error: error.message || "Failed to delete grocery item" });
  } finally {
    await prisma.$disconnect();
  }
}
